### ISSUE TITLE
Establish contact with first round of external funds

### ISSUE THREAD

**Issue by dazuck** [3box/ops#10]
TBD if this is actual investors or set of intermediaries/test runs first -- to be decided with founders.

**Comment by dazuck** [comment]
@michaelsena I've sent to ~80% of mine in wave 1, using a modified version of this email (first 2 paragraphs change significantly each time but its quick) - https://www.notion.so/threebox/Pitch-81e65253c8b34775871b040147004188. 

You've got 8 you own in round 1 here, think you can send in next day or so? https://www.notion.so/threebox/e24e7649185f433396c5dfcfd0fb8df0?v=8843a39d8cf84d8aa7be244ec3d652f8

**Comment by michaelsena** [comment]
@dazuck I sent all but one of mine because there's an outstanding question. Left a note in the Notion doc.

**Comment by michaelsena** [comment]
@dazuck this was still in progress bc I asked a question and had not completed...

**Comment by dazuck** [comment]
@michaelsena had just responded in notion and kicked that one to later

**Comment by michaelsena** [comment]
cool thanks! @dazuck
