### ISSUE TITLE
Gather all 3Box expenses & accounts 

### ISSUE THREAD

**Issue by dazuck** [3box/ops#112]
Send to Danny 
(1)  any expenses you've had sine Jan 1 (totals are fine if you'd rather not share details), 
(2) receipts of any flights you booked with Concur, 
(3) details for any accounts you're aware of that we currently pay for through Consensys and will have to transition

[] Danny
[ ] Sena
[ ] Joel
[ ] Zach
[ ] Kenzo

**Comment by zachferland** [comment]
no expenses, sent (forwarded email) receipt of flights (only flight since jan 1, unless you need others further back as well), no accounts

**Comment by dazuck** [comment]
@oed i know you're at a conference but let me know if you have anything major here plz
