### ISSUE TITLE
Project infrastructure/software costs 

### ISSUE THREAD

**Issue by dazuck** [3box/ops#118]
We need to develop a rough understanding of possible cloud computing/storage costs. Projected steps: 
1. Understand drivers of cost and which matter (# of dev users; # of end users; amount of storage used; frequency of usage;...) 
2. Decide on simple cost equation based on what matters most
3. Plug in for user growth projections and gut check 

Follow-up: get input/gut-check from a team with experience on this (e.g., infura)

**Comment by dazuck** [comment]
@oed or @zachferland would be great to collab for 30 min with one of you on this early next week. Any volunteers?

**Comment by zachferland** [comment]
@dazuck Im glad to, I was also just starting to try get a better idea of costs of our new scaling arch

**Comment by dazuck** [comment]
thanks! Will find some time for us. and we'll keep it simple to start.
