### ISSUE TITLE
Create Gitcoin bounty for integrating 3Box into Giveth

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#141]
At a minimum, getProfile. If possible, also set/update image and name.

**Comment by mattlockyer** [comment]
https://www.notion.so/threebox/Gitcoin-Bounty-generic-47e20a084f58444496efc2b4b07036c2

@michaelsena @dazuck @oed Can you provide some comments on this and I'll get it posted ASAP?

I don't have DAI, Griff said he would send it. Still need to get Ameen to commit... but the wheels are turning!

**Comment by mattlockyer** [comment]
Switch this to Giveth @michaelsena 

It's ready to go

**Comment by michaelsena** [comment]
Made some small updates, now good to go @mattlockyer 👍

**Comment by michaelsena** [comment]
Update here: I'm still working on this story

**Comment by michaelsena** [comment]
@oed here's the link to the bounty - would be helpful to have you outline how the code would work for the sections I tagged you in. https://www.notion.so/threebox/Giveth-Bounty-6ba42d7a3a464aa79594f9bdd455ac8a

**Comment by oed** [comment]
@michaelsena I don't think you have tagged me anywhere?

**Comment by michaelsena** [comment]
@oed retagged you in two sections in the doc
