### ISSUE TITLE
Publish community update 7

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#15]
https://www.notion.so/threebox/Community-Update-7-068e1a6351644a33a970c6ced188c709

**Comment by michaelsena** [comment]
Making final edits here: https://medium.com/@3box/investing-in-performance-f74ff9a2b8e9

Will publish tomorrow morning

**Comment by oed** [comment]
https://www.ebay.com/itm/10pcs-lot-Universal-Anaglyph-Cardboard-Paper-Red-Blue-Cyan-3D-Glasses-For-Movie/252779006227?epid=11007024036&hash=item3adacd8913:g:rlgAAOSw4CFYprJK:rk:20:pf:0
😂
