### ISSUE TITLE
1 DeFi Integration Commitment

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#180]

**Comment by mattlockyer** [comment]
Moloch!

https://www.notion.so/threebox/Moloch-09-04-ddb639e053c542adb58a200b5a3ce65e

**Comment by mattlockyer** [comment]
Rahul Sethuram
@RHLSTHRM

He will join Discord soon, if not already

**Comment by rhlsthrm** [comment]
Joined the Discord!
