### ISSUE TITLE
4 Games Integration Commits

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#181]

**Comment by mattlockyer** [comment]
Spoke to Axie and reached out to friends to source more warm intros.

**Comment by mattlockyer** [comment]
Mintables!

https://www.notion.so/threebox/Mintables-11-4-3b8a7109866447d987af2ee66fbceacc

**Comment by mattlockyer** [comment]
Update on projects:
Mintable (on roadmap)
Alex from OpenSea (warm reception, needs push, see notes)
Mike from Loom (aware, but team has zero time RN, interested in pushing game titles to Loom Network)
Axie Affinity (doing something similar, needs push, backend infra replacement play, they will want to skin themselves)
Axiom / CK (Michael and Danny)
These intros were hard to source, no one seemed to know any of the game teams. Tried to go wider with NFTs / OpenSea.

**Comment by prestonattebery** [comment]
Joined :)
