### ISSUE TITLE
Migrate away from ConsenSys

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#192]
When you're done, check your box:

- [x] JOEL
- [x] Resignation letter
- [ ] Goodbye emails/slack messages (if desired) 
- [x] Check to make sure of no accounts dependent on Consensys email 
- [x] Test your email forwarding 
- [x] Ensure drive, calendar, emails, etc. are properly ported and saved
- [x] SAVE YOUR PERSONAL 1PASSWORD VAULT 
- [ ] When done with all others, remove yourself from this story 
------

- [ ] MICHAEL
- [x] Resignation letter
- [x] Write a check to 3Box Inc, dated 4/19, for price of your initial shares
- [x] Goodbye emails/slack messages (if desired) 
- [x] Check to make sure of no accounts dependent on Consensys email 
- [x] Test your email forwarding 
- [x] Ensure drive, calendar, emails, etc. are properly ported and saved
- [x] SAVE YOUR PERSONAL 1PASSWORD VAULT 
- [x] Ensure 3Box Google Data Studio is properly copied over
- [ ] When done with all others, remove yourself from this story 
------

- [x] ZACH
- [x] Resignation letter
- [x] Write a check to 3Box Inc, dated 4/19, for price of your initial shares
- [x] Goodbye emails/slack messages (if desired) 
- [x] Check to make sure of no accounts dependent on Consensys email 
- [x] Test your email forwarding 
- [x] Ensure drive, calendar, emails, etc. are properly ported and saved
- [x] SAVE YOUR PERSONAL 1PASSWORD VAULT 
- [x] When done with all others, remove yourself from this story 

------

- [ ] DANNY
- [x] Resignation letter
- [x] Write a check to 3Box Inc, dated 4/19, for price of your initial shares
- [x] Goodbye emails/slack messages (if desired) 
- [x] Check accounts: Zapier, Hotjar, Discord, Github, Zenhub, Notion, Docsend
- [x] Test your email forwarding 
- [x] Ensure drive, calendar, emails, etc. are properly ported and saved
- [x] Share spin-out news with Consensys at bi-weekly
- [ ] Send email to mesh with contact info etc. 
- [x] SAVE YOUR PERSONAL 1PASSWORD VAULT 
- [ ] Confirm all are done and close story

**Comment by dazuck** [comment]
@zachferland @oed  @michaelsena migration of gsuite stuff has begun. Please be careful to save all things from hear out in 3Box accounts rather than Consensys b/c anything from here out may be missed.

**Comment by dazuck** [comment]
@zachferland @oed @michaelsena  all of your Consensys emails should now be auto-forwarding to your 3Box email accounts. Please confirm this is the case (send a test email + spot check a few you've received today) and check your box above if so. Or let me know if that's not happening.

**Comment by zachferland** [comment]
are we doing a group/3box farewell message/email to the entire mesh?

**Comment by dazuck** [comment]
@zachferland that's a good idea. I was planning to share in bi-weekly next week, and then can also send out a mesh-wide email with all our emails + discord.

**Comment by dazuck** [comment]
@zachferland @oed @michaelsena you should all have an email/shared drive from Omari with your Google Suite Takeout. Please check it out and confirm you've received and downloaded it (new item above to check off)> 

3 options for what to do with this data and migrating to 3Box's gsuite: 
1. Keep the files secure in case needed later, but just start afresh in 3Box 
2. Upload specific, needed items -- (e.g., import calendar in gcal, copy in gdrive files) 
3. Request that I do a migration of your old account to your new account. Having done this myself, I don't recommend it - I don't need much old stuff and it's more to wade through now. If you want to do this though, lmk and we need to do it together to sync on a 10-minute authorization code.

**Comment by oed** [comment]
I'll do option 4: Don't download files an be paranoid that they contain viruses.

**Comment by dazuck** [comment]
haha okay @oed fair. Just make sure you have anything that may be important in your history.

**Comment by dazuck** [comment]
@zachferland @michaelsena @oed reminder to please have this done ASAP. When all that remains is optional slack messages etc. then please mark that off so I can close this knowing we're good on the true dependencies. We should be ready to be kicked out by EOD Wednesday even if we won't actually be on that day.
