### ISSUE TITLE
Confirm + order swag for Ethereal + Blockchain week 

### ISSUE THREAD

**Issue by dazuck** [3box/ops#201]
- [ ]  t-shirt (joe to wear onstage?) 
- [x] business cards
- [x] more stickers?

**Comment by dazuck** [comment]
@michaelsena feel free to reassign this to me but assume it's easier to just do. Bad timing I know but at least want to confirm we have a shirt for Joe and business cards you're comfortable handing out.

**Comment by michaelsena** [comment]
biz cards ordered for michael and danny

**Comment by michaelsena** [comment]
Ordered stickers
