### ISSUE TITLE
PH: spinout announcement 

### ISSUE THREAD

**Issue by dazuck** [3box/ops#206]
- [ ] decide timing (MS) 
- [ ] outline content (MS draft share with DZ for input) 
- [ ] share with investors/stakeholders for input / go (DZ) 
- [ ] finalize content (MS) 
- [ ] Final review (DZ) 
- [ ] line up press (MS on point, DZ aid) (coindesk, techcrunch, Consensys PR, https://www.forbes.com/sites/michaeldelcastillo/2019/04/29/consensys-spins-off-ethereum-startup-truffle-to-take-blockchain-to-big-business/?ss=crypto-blockchain#55fe9502e21d, the block, token economy, defi weekly, .community ..)

**Comment by michaelsena** [comment]
closing duplicate
