### ISSUE TITLE
Publish "Announcing Our Seed Investment"

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#232]
- [x] decide timing (MS)  -- Jun 20
- [x] Outline post (MS)
- [x] Create first draft of post (MS draft share with DZ for input): https://www.notion.so/threebox/Send-Press-Release-for-Seed-Investment-e8f0eaff8a774eecb5d875907cfc4f00
- [x] share with investors/stakeholders for input / go (DZ) 
- [x] Update draft based on stakeholder input (DZ)
- [x] finalize content (MS) 
- [ ] Final review (DZ) 
- [ ] line up press (MS on point, DZ aid) (coindesk, techcrunch, Consensys PR, https://www.forbes.com/sites/michaeldelcastillo/2019/04/29/consensys-spins-off-ethereum-startup-truffle-to-take-blockchain-to-big-business/?ss=crypto-blockchain#55fe9502e21d, the block, token economy, defi weekly, .community ..) https://www.notion.so/threebox/4f4e291b3e0a4fb3971b1d3c4549a989?v=217bd7af987949acbf62d2f26c2351e9
- [ ] email investor list on mailchimp with this announcement, links to press mentions, and our 6 month roadmap

**Comment by dazuck** [comment]
@michaelsena  did you intentionally move this from upcoming to backlog? Moving back up. 

Also can you confirm the tasks are what you want for collab? I'm fine with that just want enough time to get input, and I have ~40 hours of flights coming up so happy to take on the outline drafting or content drafting steps if you want me to.

**Comment by michaelsena** [comment]
I did because we won't publish it until the following sprint. But I guess there's a lot of work in here that will start this sprint. @dazuck

**Comment by michaelsena** [comment]
@dazuck - I added a few steps above to the collaboration is cleaner. Roles should be assigned in the right space.

**Comment by dazuck** [comment]
Looks good.

**Comment by michaelsena** [comment]
@dazuck ready for your review. I created one post that will function as the press release and we can use it as our post too. https://www.notion.so/threebox/Send-Press-Release-for-Seed-Investment-e8f0eaff8a774eecb5d875907cfc4f00
