### ISSUE TITLE
Create summary

### ISSUE THREAD

**Issue by dazuck** [3box/ops#25]
Create a 1-pager to share with people for an at-a-glance view of 3Box 

See Pegasys for a good example.

**Comment by dazuck** [comment]
- Elevator pitch - product, team biz in 1-3 paragraphs very clearly.
- Exec summary-1-3 pages for brand new ppl
    - All about substance
    - Problem you are solving, why your approach is better, etc

**Comment by michaelsena** [comment]
Andreas Freund asked for it

**Comment by dazuck** [comment]
Splitting 1-pager and summary and closing summary
