### ISSUE TITLE
Publish "Profile Hovers for React Apps"

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#261]

**Comment by michaelsena** [comment]
Medium draft [HERE](https://medium.com/@3box/3box-profile-hovers-v2-7f13529094ad). Still in progress.

**Comment by oed** [comment]
Few things:
* Really like the simplicity of this :D 
* Code snippets as gists? (make sure that they are *.jsx for correct syntax highlighting)
* Can you please use my current eth address: `0x5c44e8982fa3c3239c6e3c5be2cc6663c7c9387e` 🙂
