### ISSUE TITLE
Update pitch for external use

### ISSUE THREAD

**Issue by dazuck** [3box/ops#28]

**Comment by dazuck** [comment]
Close "V1" of external pitch to start sharing and stop spending as much dedicated time iterating.

**Comment by dazuck** [comment]
@michaelsena didn't get to quite everything but would appreciate your high level spin through when you have a chance for reactions to the changes - what feels good, what feels still 'far' off

**Comment by dazuck** [comment]
@michaelsena link (note that i moved the current version to the top) - https://docs.google.com/presentation/d/1_yZYzs1ZBeK99xhF_5joWt6DKEGOYwnryLV5FJ7ZLUw/edit#slide=id.g4b4c2f0d6e_0_727

**Comment by michaelsena** [comment]
@dazuck back to you! Thanks :)
