### ISSUE TITLE
Add coding and engineering questions to interview bank

### ISSUE THREAD

**Issue by dazuck** [3box/ops#291]
- [ ] add general questions https://www.notion.so/threebox/610228b0cdef4f3da16a6e5b192999ff?v=89e80e31e30a402bb09d01e65b49d606
- [ ] create take home for immediate use (collab w/ DZ)

**Comment by dazuck** [comment]
@oed @zachferland adding this to the backlog for next sprint, but oed keep in mind you do have an interview Monday so may want to at least chat/start before then

**Comment by oed** [comment]
@dazuck Added a bunch of Qs to the techCom column.
