### ISSUE TITLE
Publish Threads v2 Post

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#293]

**Comment by michaelsena** [comment]
@oed or @zachferland this post is ready for your eyes. Not 100% complete yet, but mostly there. Will release a day after 3Box.js 1.9 goes out. https://medium.com/3box/3box-threads-a-chat-system-for-decentralized-apps-7a77be49680c

**Comment by oed** [comment]
Looks good overall! Why "chat system" over "messaging system" in the title? The latter seems more general.

**Comment by michaelsena** [comment]
Agreed that `messaging system` is more general, but I have seen tweets in reference to people asking about a decentralized `chat system`. Goin to experiment with language. I use both in the body text, so this is just a header. @oed
