### ISSUE TITLE
Communicate "soft fork" breaking upgrade of 3Box.js

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#294]
Communication Progress:
- [x] Tweet on 6/5/19: https://twitter.com/3boxdb/status/1136359464993533952

--
Medium post
Tweets
Discord announcement
ConsenSys slack
Mailchimp

**Comment by michaelsena** [comment]
@oed can you write a one paragraph blurb that I can use to learn more about what needs to be communicated?

**Comment by michaelsena** [comment]
@oed have any content for me? I guess it doesn't need to be announced today since we're pushing back the Threads v2 release?

**Comment by oed** [comment]
With 3box-js 1.9.0 there is a breaking change in an underlying package (orbitdb). This means that:
* The old version will no be able to see changes made by the new version in `profile` and `spaces`
* The new version will be able to see all updates made by the old version
* The old version of threads are not viewable in the new version
* The old version will not be able to fetch and see the new version of threads

I think this covers everything. Let me know if I should clarify anything.
