### ISSUE TITLE
Submit PR to be added to tryethereum.today

### ISSUE THREAD

**Issue by dazuck** [3box/ops#303]
https://twitter.com/kermankohli/status/1135428950367166464

**Comment by kuhnchris** [comment]
![grafik](https://user-images.githubusercontent.com/761911/58801451-e87fdf00-860a-11e9-937e-7a95c7f1243a.png)

https://github.com/kuhnchris/try-ethereum

**Comment by dazuck** [comment]
amazing @kuhnchris thanks!
