### ISSUE TITLE
Marketing for July Community Call

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#309]
- [ ] Create schedule
- [ ] Create Mailchimp group and signup form
- [ ] Invite projects to present
- [ ] Send Initial Invitations on [ ] twitter [ ] medium [ ] discord [ ] mailchimp [ ] consensys slack [ ] Reddit
- [ ] Send Second Invitations on [ ] twitter [ ] discord
- [ ] Confirm projects to present
- [ ] Send Final Chance to Signup on [ ] twitter [ ] discord [ ] mailchimp [ ] consensys slack
- [ ] Send Reminder to RSVPs [ ] discord [ ] mailchimp
- [ ] Send schedule to core team
--
- [ ] Send video recording to Mailchimp group, discord, and twitter

**Comment by kuhnchris** [comment]
Maybe try cross-posting with the gitcoin guys, they also do community calls, and I guess the people interested in these kind of things do certainly overlap.

**Comment by michaelsena** [comment]
Good point, @kuhnchris will ping their team closer to the date. We'e roughly targeting July 9 as of now.

**Comment by michaelsena** [comment]
closing duplicate
