### ISSUE TITLE
Post Bounty to Export Gitcoin History to 3Box

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#312]
## Description
This is a bounty that we will post on Gitcoin. This bounty describes how 3Box will integrate into Gitcoin and allow Gitcoin users to export their Gitcoin history to a 3Box space, where it can be used on other platforms. :rocket:

**Comment by kuhnchris** [comment]
Gitcoin "history"? I've worked quite a while with them, not entirely sure what you mean by "history", except maybe previous bounty descriptions? Else the interactions would show up in the activity log?

**Comment by michaelsena** [comment]
We met you through Gitcoin 💚@kuhnchris! And we were thinking something like exporting titles of bounties you've funded and funding amount, bounties you've picked up and abandoned or completed, and possibly even something related to their rating system they seem to have represented by stars on your profile.

**Comment by michaelsena** [comment]
Basically the idea is that, if stored on 3Box, it's easy for the user to carry it around with them and use it on other services easily. Especially more valuable if users are linking multiple ethereum accounts to their 3Box they could share this work history across their diff accounts

**Comment by michaelsena** [comment]
Posted an initial issue on Gitcoin, we're coordinating on the spec here: https://github.com/gitcoinco/web/issues/4651

Once that is complete, we will post the bounty issue.

**Comment by michaelsena** [comment]
closing, stale and completed
