### ISSUE TITLE
Create initial analytics charts

### ISSUE THREAD

**Issue by dazuck** [3box/ops#321]
KPIs that we can do without extra dev work

**Comment by dazuck** [comment]
@oed guessing this should probably be for early next sprint, right? If so, i'll separate into a (1) prep google data studio for visuals, and (2) populate with analytic data and do them separately.

**Comment by michaelsena** [comment]
@oed and @zachferland we specced this the other day and said it should be 2 charts this sprint. Which 2? Can you please update the description and title above with that info? TY! 🙏

**Comment by michaelsena** [comment]
closing duiplicate
