### ISSUE TITLE
Consume analytic events

### ISSUE THREAD

**Issue by oed** [3box/ops#326]
For aggregate `get`

If easy also add aggregate `set`

**Comment by zachferland** [comment]
Was able to show all the aggregates in Mixpanel. Was able to connect redshift as data source to google data studio, but when i try to to create formula value the tools constantly through errors saying it can be added at this time. There is also more formatting for data in google studio required, while for mixpanel, segment will map data to the consumable form for the tool by default.

**Comment by zachferland** [comment]
Closing, as this was connected to multiple destinations and few charts were created. Although not in data studio yet (data is connect though) stories in next sprint will decide which tools we go with going forward
