### ISSUE TITLE
Share docs for knowledgebase with EthBerlin

### ISSUE THREAD

**Issue by dazuck** [3box/ops#361]
![image.png](https://images.zenhubusercontent.com/5b2d0d16ec017908afbeb74d/5bb42ac0-5028-434c-ba71-3d3715e7d16f)

**Comment by michaelsena** [comment]
Seems the `Knowledge Base` is just the bounties themselves: https://github.com/ethberlin-hackathon/ETHBerlin-KnowledgeBase
