### ISSUE TITLE
Marketing for Berlin Meetup or Drinks

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#375]
- [ ] Create Event Graphic
- [ ] Create Eventbrite event
- [ ] Write *brief* medium post
- [ ] Spread on social (Twitter, Discord, Cons Members...)

**Comment by oed** [comment]
We should also submit the event here: https://www.blockchainweek.berlin/
cc @dazuck

**Comment by dazuck** [comment]
Yep will do once ready

**Comment by michaelsena** [comment]
not relevant
