### ISSUE TITLE
Book flights to Berlin + Offsite

### ISSUE THREAD

**Issue by dazuck** [3box/ops#378]
We should book these ASAP. Flights are already expensive and we need to plan really effectively around this event given the amount going on and the amount we're committing to it. 

Please select a flight and clear with DZ to book. Ideally use Brex Travel Portal but also check Google Flights for cheaper options. 

GUIDELINES
Flying in to Berlin: 
1. Must be in Berlin and ready to work by morning of 8/21
2. Encouraged to be there by the 21st or earlier so we can stagger work and attend DappConn (21-23 -- we have free tickets) and other events, plus host a meetup ourselves
3. We'll provide housing beginning the 18th so can show up then and work from Berlin + attend events 

Flying out of Warsaw: 
1. Can fly out beginning Thursday the 29 midday
2. We'll provide housing through the 30th for those who wish to stay into Friday. Welcome to stay longer and fly back later too (Warsaw is fun and very cheap). 

For full (evolving) calendar: https://www.notion.so/threebox/ba4a098b06e3437082430c5217bf501f?v=eadbc61ac1b346fb8eddb086133495d6 and https://www.blockchainweek.berlin/20-august

**Comment by dazuck** [comment]
@zachferland @oznekenzo @michaelsena this is now ready. lmk if you have any questions

**Comment by dazuck** [comment]
i'll share my flights as soon as i book, hopefully tonight or tomorrow

**Comment by michaelsena** [comment]
I booked my flights. 👍Thanks

**Comment by dazuck** [comment]
@zachferland  @oznekenzo  FYI, if you haven't booked (a) please do, (b) flights into Berlin are WAY cheaper if you book a return ticket, even if that return is from another city (aka Warsaw). 

I thought flights were pretty much RT = 2 x 1 way now, but a good 1-way flight for me NY-Berlin was $2000 and when i plugged in a random return it fell to $700..strange, but make sure you do this. 

I land in Berlin Sunday morning, out from Warsaw Thursday late afternoon

**Comment by oznekenzo** [comment]
Will buy tomorrow

**Comment by oznekenzo** [comment]
Ahhh, I have to wait a day to hear back about family stuff that might change travel plans

**Comment by oznekenzo** [comment]
Tickets bought: going to Berlin early, arriving morning of 16th.  I'll get a personal Airbnb for the weekend.  @oed LMK if you're doing anything that weekend!  Heading to Warsaw at noon on the 26th.  Staying at my cousins in Warsaw until the 31st, after everyone leaves.
