### ISSUE TITLE
Plan EthBerlin Meetup

### ISSUE THREAD

**Issue by dazuck** [3box/ops#386]
is consensys organizing anything? other spokes? 

general, or panel, or more? 

https://docs.google.com/forms/d/e/1FAIpQLSdP0EdmT6Hi-RKF3Q6aQeks1Pd93MKehGRyUm6SPipXAAFfCA/viewform

can wendy/northzone help? 

- [x] Venue
- [x] Topic
- [x] Panel
- [x] Create eventbrite
- [x] Submit to blockchain week calendar
- [ ] Plan for promoting

**Comment by michaelsena** [comment]
We need a theme or topic for the meetup. I'm thinking, The Web3 Experience (usability for users and devs). All projects that we co-sponsor with should have something to do with web3 usability, and those projects would be on the panel.

I think my preferred format is casual 30 minutes of mingling with food/drink, 15 minutes of moderated panel intro/project overviews, a 30 min panel on web3 usability, and after drinks and hanging out more.

Dunno what the best venue for something like this would be, but I'm sure we can find a cool cafe or something that would let us bring alcohol and food.

  Evaluate and pick teams to have it with (should prob be some Cons and some non to attract widest audience). Maybe like Infura, 3Box, Dapper, WalletConnect, MetaMask, Uniswap, Maker, Fortmatic, Portis, Wyre, etc.
  Evaluate and pick date
  Evaluate and pick place
  Confirm all of this
