### ISSUE TITLE
plan retreat at high level 

### ISSUE THREAD

**Issue by dazuck** [3box/ops#405]
- [ ] draft agenda
- [ ] share for team input
- [ ] assign owners and reviewers to finalize

**Comment by michaelsena** [comment]
@dazuck will make more specific

**Comment by dazuck** [comment]
@michaelsena @zachferland @oznekenzo  please review in next couple days https://www.notion.so/threebox/BoxCon-1-f42a1733c6154e8d8400f813c14dd196
