### ISSUE TITLE
Set up the appropriate data points in Google Data Studio

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#41]
This issue includes taking raw table data in redshift and applying queries, etc, so that the output is actual data points needed to plot a dashboard.

**Comment by michaelsena** [comment]
Okay thanks, I'll try creating some tomorrow!

**Comment by michaelsena** [comment]
Have you checked in on these dashboards since you created them? We should be looking at these daily. Can you please own this from a quality perspective and make sure everything is working?

**Comment by michaelsena** [comment]
@c-castillo after you dig in and figure out what's going on, can you update here? ty! 👍

**Comment by c-castillo** [comment]
@michaelsena After some configuration change, segment sync with redshift start worked again. We have new data in the dashboards including the days that were missing

**Comment by oed** [comment]
@michaelsena anything still missing here?
