### ISSUE TITLE
Complete mandatory trainings

### ISSUE THREAD

**Issue by dazuck** [3box/ops#461]
Everyone must complete this by Oct 9: https://www.notion.so/threebox/Sexual-Harassment-Prevention-Training-d649b90ed90943b198e6f64bf76f8c3b

It can be done relatively quickly and mostly offline (in flight) if you prepare.

**Comment by dazuck** [comment]
@oed did you do this? don't see a typeform response from you. Looks like i may have unassigned you by accident?

**Comment by dazuck** [comment]
@michaelsena this really needs to be done ASAP.

**Comment by oed** [comment]
Hm, I did do it and sent the typeform.

**Comment by michaelsena** [comment]
Done @dazuck
