### ISSUE TITLE
Submit for UX awards (by 9th) 

### ISSUE THREAD

**Issue by dazuck** [3box/ops#473]
https://devcon.org/ux-awards

@oznekenzo @michaelsena  do one of you want to submit here? Even better would be to get someone in our community to do it. Or can just copy/paste tweets about UI (JSW, Luis, etc.)

**Comment by oznekenzo** [comment]
Hmmmm if anything I would put forward our web3 context handling - wallet logins & switching (a lot of which is walletconnect) with our web3 login state (network + address) handling which is pretty good!

**Comment by dazuck** [comment]
Do you have time to put together an initial app today that we can look at
and submit? I think you could submit that + the drop in plugins with a
theme of 'making Web3 both powerful for users and simple for devs' or
sometbing

 I'd go to 3box Twitter and pull a couple tweet complements of our UX too.

**Comment by oznekenzo** [comment]
Will do
