### ISSUE TITLE
Prepare 10 FAQs for website

### ISSUE THREAD

**Issue by RachBLondon** [3box/ops#492]
https://www.notion.so/threebox/FAQs-4cab6c5e3f9345e08a17c37bc5fe6bb9

**Comment by michaelsena** [comment]
@RachBLondon whenever you have a moment, it's helpful to link to the Notion docs here in the GH issues so the content is easier to track down when needed :)

**Comment by RachBLondon** [comment]
Of course, makes sense 👍

**Comment by michaelsena** [comment]
@RachBLondon can you make this not private so I can provide some feedback? TY! 🙏

**Comment by RachBLondon** [comment]
Link should be public no, plus ive tagged you in notion 👍
