### ISSUE TITLE
Correctly map tracked users in mixpanel

### ISSUE THREAD

**Issue by dazuck** [3box/ops#495]
-----------
From Mixpanel: 
For some background, MTUs are different from people profiles. People profiles are people you register on your account. Monthly Tracked Users(MTU) is a different way to calculate your billing based on the number of users that perform a qualifying event each month, rather than individual people profiles or events. We track MTUs as all distinct_ids who have done at least one event in a month-long window. However, there's one main exception to this: if your users are averaging more than 1,000 events each, they will count as additional users. As an additional resource, I'll also pass along this article from our help documentation about Billing-for-Monthly-Tracked-Users.

As a guide, you can see from this Insight report which shows you the unique event tracks in October. From this Insight report, you can see the top unique events. It looks like you are tracking a high volume for the events api_get_config and pin_db_address. With that in mind, you may want to review the events tracked -- api_get_config and pin_db_address in order not to use up your quota.

**Comment by zachferland** [comment]
Re using this story, adding points and really blocking time for it now. Changing title.

**Comment by zachferland** [comment]
https://github.com/3box/3box-api/pull/10
