### ISSUE TITLE
Conduct and document 5 dev interviews

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#508]
Likely record the interviews on Zoom, so we can always go back and watch. Also a written summary of the interview (ie main takeaways, developer vitals, interesting things, etc)

Completed
- [x] Kames CG
- [x] Jon S
- [x] Frank P
- [x] Dan M
- [x] Lauren

**Comment by RachBLondon** [comment]
From today's interview https://www.notion.so/threebox/Frank-Polster-452730796dd44da8a50eff6dfc95f69a
