### ISSUE TITLE
Prepare checklist & roadmap for entity formation + transition 

### ISSUE THREAD

**Issue by dazuck** [3box/ops#52]
By end of this story should have a good sense of 
1. All steps that will be taken to transition to our own entity
2. Rough order of operations
3. Biggest risks and outstanding questions 
4. Path to complete this and any support needed externally

**Comment by michaelsena** [comment]
Waiting on Min separately

**Comment by dazuck** [comment]
We have the checklist (basically), now need the roadmap and timeline (next sprint)
