### ISSUE TITLE
2020 event schedule & strategy (first pass) 

### ISSUE THREAD

**Issue by dazuck** [3box/ops#526]
This certainly will not be final, but we should proactively look at the events we think we want some presence at next year so we can prioritize, plan, and get speaker slots. 

Likely process (in Notion calendar): 
1. Compile list of events across categories 
2. Review with team and external 'experts' in each category 
3. Put together initial plan and set reminders for speaking and booking opps 

Categories we should look at, in rough priority: 
- [x] Ethereum conferences and hackathons 
- [x] Other crypto - conferences, blockchain weeks, hackathons 
- [x] Identity and data - IIW, MyData, ... 
- [x] Distributed data/web - IPFSCamp, DWeb, DTN..
- [x] Developer communities - languages (Java, JS), 
- [x] Builder events - ProductHunt, NoCode communities 
- [x] Leading events by aligned industry leaders (StackOverflow)

We likely will do very few further down the list but it's worth starting to get a sense and seeing where we can be an early web3 tech to make inroads there.

**Comment by dazuck** [comment]
https://www.blocksocial.com/events/

**Comment by RachBLondon** [comment]
Gitcoin are running a take back the web hackathon Jan 9 - 23. Could be a good fit with user controlled data.
