### ISSUE TITLE
Map cost drivers to BI drivers

### ISSUE THREAD

**Issue by dazuck** [3box/ops#547]
Create a spreadsheet that models cost according to BI drivers (users), driven by underlying costs (CPU, etc.) 

https://www.notion.so/threebox/Metrics-planning-nov-2019-d61498a23f9448aabec4c39f05f3ed6e

**Comment by oed** [comment]
@dazuck to list BI drivers

**Comment by dazuck** [comment]
BI drivers: 
* End Users (DIDs)
* Amount of data at rest in the network 
* Data throughput daily 
* Data transactions - set
* Data transactions - get 
* Number of apps setting data
less critical but still relevant 
* Number of spaces, threads, DBs (or some other abstraction that would impact cost) 
* Number of nodes syncing 
* Number of node providers

@msterle @zachferland  would it be helpful to set up a call with an AWS solution architect to see how they suggest modeling this out? I'd guess they have a lot of experience with this kind of thing? 

FYI relevant podcast i found interesting: https://castbox.fm/vb/102288350

**Comment by dazuck** [comment]
@msterle @zachferland  how are we feeling about this story? 

plz let me know if you want me to connect you to the AWS solution architect to talk through approach and model, as I imagine that will need some lead time.

**Comment by zachferland** [comment]
havent picked this up yet, dont feel the need for this round, but @msterle can say otherwise as well, @msterle want to sync and spend some time on this on wed?

**Comment by zachferland** [comment]
do other stories replace this now? cc @msterle

**Comment by zachferland** [comment]
Closing for now, reopen if necessary
