### ISSUE TITLE
Draft spec for boilerplate repo (create-3box-eth)

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#588]
This would allow other devs to get started building with 3Box and Ethereum very easily.

The spec should include:
- [x] Libraries that will be included in the boilerplate (React, 3Box.js, some EthProvider library, ...)
- [x] Anything else @RachBLondon?

**Comment by RachBLondon** [comment]
After my call with Kenzo last week https://www.notion.so/threebox/Boilerplate-Spec-c1c75130eaac45fbb1aaeccf95ba2f1d
