### ISSUE TITLE
Decide Who Speaks On Panel and Presents at ETH Denver

### ISSUE THREAD

**Issue by RachBLondon** [3box/ops#593]
5 Tracks for Content in 2020: 1) DeFi 2) DAOs & Token Engineering 3) Gaming & Usability 4) Protocols & Interoperability 5) Public Good & Social Impact
Workshops: These will take place ALL DAY on Friday (8AM-5PM) and the first half of Saturday (8AM-12PM). 
Panels: These will take place later in the morning on Saturday and continue through Saturday afternoon (11AM-5PM). 
[See FAQs](https://docs.google.com/document/d/19n7IK1TIZSjrYVQ49LZNenA8w9hPpDGZjKJV4rQWG6U/edit#)
- [ ] Speak to Matt beforehand (meeting booked 6/1)
- [ ] Send over assets once decided Please send these to [sponsors@ethdenver.com](mailto:sponsors@ethdenver.com):
⋅⋅⋅A headshot for the person/people you'd like to highlight on our site in our speakers/judges section. The number of headshots is determined by your sponsorship level as described in the FAQ.
⋅⋅⋅ a .PNG project/company logo
⋅⋅⋅ ***AND*** a .SVG project/company logo (hi res for banners)

**Comment by michaelsena** [comment]
duplicate
