### ISSUE TITLE
Create presentation for ETHDenver Workshop

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#627]

**Comment by RachBLondon** [comment]
[Presentation](https://docs.google.com/presentation/d/1L3fWuUVmNAishiupL9SxYl2OT3Uce0L8jLz9nDWGouE/edit?usp=sharing)
[Workshop](https://www.notion.so/threebox/ETHDenver-Workshop-6aa44f89d70a43009df2cc931a08cf89)
