### ISSUE TITLE
Order rollup banners for Berlin office

### ISSUE THREAD

**Issue by michaelsena** [3box/ops#631]

**Comment by RachBLondon** [comment]
- These can be ordered directly to Belgium (this will save on the cost to transport as im flying Ryan air and their baggage policy is strict) I will DM you the address.
- It would also be nice to order some stickers (to hand out) and a few T Shirts (at least so we can wear on the stand)

**Comment by RachBLondon** [comment]
Print stickers can be ordered here (4 day turn around) https://www.stickermule.com
Banners (48hr turn around)  - https://www.postupstand.com/all-products/banner-stands/retractable.html?gclid=EAIaIQobChMImIu0nqaS5wIVBbTtCh1XZAVOEAAYAiAAEgKJh_D_BwE

**Comment by RachBLondon** [comment]
Ive ordered the banners

**Comment by RachBLondon** [comment]
Stickers have been ordered as well - due to arrive on Thursday
