### ISSUE TITLE
Obtain Items for ETH Denver Stand

### ISSUE THREAD

**Issue by RachBLondon** [3box/ops#645]
- [x] Flyers 
- [x] Stickers
- [x] Business Cards
- [x] Swag (T-shirts, Hoodies, Hats)
- [x] Table Cloth [in progress]
- [x] Roll Up Banners, Backdrop
- [x]  2 X monitors

**Comment by michaelsena** [comment]
@dazuck you think we should bring our monitors from nyc, or ask if we can borrow some from the consensys office in boulder or something

**Comment by michaelsena** [comment]
Placed orders for tablecloth and flyers
