### ISSUE TITLE
Funding strategy & plan 

### ISSUE THREAD

**Issue by dazuck** [3box/ops#8]
This includes a few elements which lead to a clear path for 3Box runway and funding. 
1. What are our expected expenses (over the right time period for planning) 
2. What funding do we need to support that, at what terms
3. Where do we get that funding - plan to source (internally or eternally)

**Comment by michaelsena** [comment]
Done on my part!

**Comment by dazuck** [comment]
thanks @michaelsena . Do you see any reason to hold off beginning to reach out to some of the most friendly "1s" this week?
